version: "3.8"

services:
  db:
    image: postgres:14
    container_name: water_quality_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./api
    depends_on:
      - db
    container_name: water_quality_api
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    ports:
      - "5001:5001"
    volumes:
      - ./api:/usr/src/app
    command: >
      sh -c "node seeds/seed_water_quality_data.js && node server.js"

  frontend:
    build: ./dataviz-client
    container_name: water_quality_frontend
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  db_data:
